# Generated by Django 2.1.7 on 2019-02-21 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaVkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_login', models.CharField(blank=True, max_length=100, null=True)),
                ('insta_password', models.CharField(blank=True, max_length=200, null=True)),
                ('vk_login', models.CharField(blank=True, max_length=100, null=True)),
                ('vk_password', models.CharField(blank=True, max_length=200, null=True)),
                ('vk_token', models.CharField(blank=True, max_length=300, null=True)),
                ('insta_group_list', models.ManyToManyField(to='instagram_api.InstaGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
