# Generated by Django 2.1.7 on 2019-06-04 11:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instagram_api', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('register_code', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_login', models.CharField(blank=True, max_length=100, null=True)),
                ('insta_password', models.CharField(blank=True, max_length=200, null=True)),
                ('vk_login', models.CharField(blank=True, max_length=100, null=True)),
                ('vk_password', models.CharField(blank=True, max_length=200, null=True)),
                ('vk_token', models.CharField(blank=True, max_length=300, null=True)),
                ('vk_app', models.CharField(blank=True, max_length=50, null=True)),
                ('vk_group_id', models.CharField(blank=True, max_length=50, null=True)),
                ('insta_group_list', models.ManyToManyField(blank=True, to='instagram_api.InstaGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='insta_vk_main.CustomUser')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
