# Generated by Django 2.1.7 on 2019-02-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_vk_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instavkuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='instavkuser',
            name='insta_group_list',
            field=models.ManyToManyField(blank=True, null=True, to='instagram_api.InstaGroup'),
        ),
    ]
