# Generated by Django 2.1.7 on 2019-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_vk_main', '0002_auto_20190604_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='insta_group_list',
            field=models.ManyToManyField(blank=True, to='instagram_api.InstaGroup'),
        ),
    ]
