# Generated by Django 2.1.7 on 2019-03-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_vk_main', '0003_auto_20190223_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='instavkuser',
            name='vk_app',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instavkuser',
            name='insta_group_list',
            field=models.ManyToManyField(blank=True, to='instagram_api.InstaGroup'),
        ),
    ]
