# Generated by Django 2.1.7 on 2019-03-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_vk_main', '0004_auto_20190310_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='instavkuser',
            name='vk_group_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
