# Generated by Django 2.1.7 on 2019-03-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagroup',
            options={'verbose_name': 'Instagram группа', 'verbose_name_plural': 'Instagram группы'},
        ),
    ]
